Minesweeper: src/Actions.h File Reference
Actions.h File Reference
#include "Board.h"
Macros
#define MS_FINE_CODE 0
#define MS_WIN_CODE 1
#define MS_LOSE_CODE -1
#define MS_CANNOT_FLAG_CODE -2
#define MS_CANNOT_OPEN_CODE -3
Functions
int ms_board_toggle_flag (ms_board *board, int row, int col)
int ms_board_open (ms_board *board, int row, int col)
Macro Definition Documentation
MS_CANNOT_FLAG_CODE
#define MS_CANNOT_FLAG_CODE -2
Definition at line 16 of file Actions.h.
Referenced by ms_board_toggle_flag(), ms_cell_toggle_flag(), and ms_play().
MS_CANNOT_OPEN_CODE
#define MS_CANNOT_OPEN_CODE -3
Definition at line 17 of file Actions.h.
Referenced by ms_board_open(), and ms_play().
MS_FINE_CODE
#define MS_FINE_CODE 0
Definition at line 13 of file Actions.h.
Referenced by ms_board_open_neighbours(), ms_board_status(), and ms_cell_toggle_flag().
MS_LOSE_CODE
#define MS_LOSE_CODE -1
Definition at line 15 of file Actions.h.
Referenced by ms_board_status(), and ms_play().
MS_WIN_CODE
#define MS_WIN_CODE 1
Definition at line 14 of file Actions.h.
Referenced by ms_board_status(), and ms_play().
Function Documentation
ms_board_open()
int ms_board_open (ms_board * board, int row, int col)
Definition at line 82 of file Actions.c.
References cell::is_flagged, cell::is_shown, ms_board_get(), ms_board_open_cell(), and MS_CANNOT_OPEN_CODE.
Referenced by ms_play_once().
ms_board_toggle_flag()
int ms_board_toggle_flag (ms_board * board, int row, int col)
Definition at line 34 of file Actions.c.
References cell::is_flagged, ms_board_get(), ms_board_status(), MS_CANNOT_FLAG_CODE, ms_cell_toggle_flag(), and board::nb_flags.
Referenced by ms_play_once().