Minesweeper: src/Actions.c File Reference
Actions.c File Reference
#include <stdio.h>
#include "Board.h"
#include "Util.h"
#include "Actions.h"
Functions
int ms_board_status (ms_board *board, ms_cell cell)
int ms_cell_toggle_flag (ms_cell *cell)
int ms_board_toggle_flag (ms_board *board, int row, int col)
void ms_cell_show (ms_cell *cell)
int ms_board_open_cell (ms_board *, int, int)
int ms_board_open_neighbours (ms_board *board, int row, int col)
int ms_board_open (ms_board *board, int row, int col)
Function Documentation
ms_board_open()
int ms_board_open (ms_board * board, int row, int col)
Definition at line 82 of file Actions.c.
References cell::is_flagged, cell::is_shown, ms_board_get(), ms_board_open_cell(), and MS_CANNOT_OPEN_CODE.
Referenced by ms_play_once().
ms_board_open_cell()
int ms_board_open_cell (ms_board * board, int row, int col)
Definition at line 67 of file Actions.c.
References cell::is_bombed, cell::is_flagged, cell::is_shown, ms_board_get(), ms_board_open_neighbours(), ms_board_status(), ms_cell_show(), cell::nb_neighbours, and board::nb_shown.
Referenced by ms_board_open(), ms_board_open_neighbours(), and ms_cell_show().
ms_board_open_neighbours()
int ms_board_open_neighbours (ms_board * board, int row, int col)
Definition at line 54 of file Actions.c.
References ms_board_open_cell(), MS_FINE_CODE, ms_max(), ms_min(), board::nb_cols, and board::nb_rows.
Referenced by ms_board_open_cell().
ms_board_status()
int ms_board_status (ms_board * board, ms_cell cell)
Definition at line 11 of file Actions.c.
References cell::is_bombed, cell::is_shown, MS_FINE_CODE, MS_LOSE_CODE, MS_WIN_CODE, board::nb_bombs, board::nb_cols, board::nb_flags, board::nb_rows, and board::nb_shown.
Referenced by ms_board_open_cell(), and ms_board_toggle_flag().
ms_board_toggle_flag()
int ms_board_toggle_flag (ms_board * board, int row, int col)
Definition at line 34 of file Actions.c.
References cell::is_flagged, ms_board_get(), ms_board_status(), MS_CANNOT_FLAG_CODE, ms_cell_toggle_flag(), and board::nb_flags.
Referenced by ms_play_once().
ms_cell_show()
void ms_cell_show (ms_cell * cell)
Definition at line 47 of file Actions.c.
References cell::is_shown, and ms_board_open_cell().
Referenced by ms_board_open_cell().
ms_cell_toggle_flag()
int ms_cell_toggle_flag (ms_cell * cell)
Definition at line 26 of file Actions.c.
References cell::is_flagged, cell::is_shown, MS_CANNOT_FLAG_CODE, and MS_FINE_CODE.
Referenced by ms_board_toggle_flag().