Minesweeper: src/Board.h File Reference
Board.h File Reference
Data Structures
struct cell
struct board
Typedefs
typedef struct cell ms_cell
typedef struct board ms_board
Functions
ms_board * ms_board_make (int nb_cols, int nb_rows, double bomb_ratio)
ms_cell * ms_board_get (ms_board *board, int row, int col)
void ms_board_print (ms_board *board)
void ms_board_free (ms_board *board)
Typedef Documentation
ms_board
typedef struct board ms_board
ms_cell
typedef struct cell ms_cell
Function Documentation
ms_board_free()
void ms_board_free (ms_board * board)
Definition at line 208 of file Board.c.
References board::cells, ms_matrix_free(), and board::nb_rows.
Referenced by main().
ms_board_get()
ms_cell* ms_board_get (ms_board * board, int row, int col)
Definition at line 35 of file Board.c.
References board::cells, and ms_matrix_get().
Referenced by ms_board_open(), ms_board_open_cell(), ms_board_toggle_flag(), ms_board_update_nb_neighbours(), and ms_cell_update_nb_neighbours().
ms_board_make()
ms_board* ms_board_make (int nb_cols, int nb_rows, double bomb_ratio)
Definition at line 100 of file Board.c.
References board::cells, ms_board_update_nb_neighbours(), ms_matrix_make(), board::nb_bombs, board::nb_cols, board::nb_flags, board::nb_rows, and board::nb_shown.
Referenced by main().
ms_board_print()
void ms_board_print (ms_board * board)
Definition at line 178 of file Board.c.
References board::cells, MS_BOTTOM_FORMAT, ms_line_print(), ms_matrix_print(), board::nb_bombs, board::nb_cols, board::nb_flags, board::nb_rows, board::nb_shown, and NEW_LINE.
Referenced by ms_play(), and ms_play_once().