Minesweeper: src/Board.c File Reference
Board.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "Board.h"
#include "Util.h"
Macros
#define SPACE " "
#define NEW_LINE "\n"
#define MS_NUMBER_FORMAT "%d"
#define MS_NUMBER_ZERO_FORMAT " "
#define FLAG "X"
#define BOMB "*"
#define HIDDEN "."
#define MS_CELL_SEPARATOR " | "
#define MS_LINE_PREFIX "\n "
#define MS_LINE_FORMAT "----"
#define MS_ROW_INDEX_FORMAT "\n%3d %s"
#define MS_COL_INDEX_FORMAT "%3d "
#define MS_BOTTOM_FORMAT "%d shown, %d/%d flagged, %d hidden"
Functions
ms_cell * ms_row_get (ms_cell *cells, int col)
ms_cell * ms_matrix_get (ms_cell **cells, int row, int col)
ms_cell * ms_board_get (ms_board *board, int row, int col)
void ms_cell_update_nb_neighbours (ms_board *board, int row, int col)
int ms_board_update_nb_neighbours (ms_board *board)
ms_cell ms_cell_make (double bomb_ratio)
ms_cell * ms_row_make (int nb_cols, double bomb_ratio)
ms_cell ** ms_matrix_make (int nb_rows, int nb_cols, double bomb_ratio)
ms_board * ms_board_make (int nb_cols, int nb_rows, double bomb_ratio)
void ms_cell_print (ms_cell cell)
void ms_row_print (ms_cell *cells, int row_index, int nb_cols)
void ms_header_print (int nb_cols)
void ms_line_print (int nb_cols)
void ms_matrix_print (ms_cell **cells, int nb_rows, int nb_cols)
void ms_board_print (ms_board *board)
void ms_row_free (ms_cell *cells)
void ms_matrix_free (ms_cell **cells, int nb_rows)
void ms_board_free (ms_board *board)
Macro Definition Documentation
BOMB
#define BOMB "*"
Definition at line 12 of file Board.c.
Referenced by ms_cell_print().
FLAG
#define FLAG "X"
Definition at line 11 of file Board.c.
Referenced by ms_cell_print().
HIDDEN
#define HIDDEN "."
Definition at line 13 of file Board.c.
Referenced by ms_cell_print().
MS_BOTTOM_FORMAT
#define MS_BOTTOM_FORMAT "%d shown, %d/%d flagged, %d hidden"
Definition at line 19 of file Board.c.
Referenced by ms_board_print().
MS_CELL_SEPARATOR
#define MS_CELL_SEPARATOR " | "
Definition at line 14 of file Board.c.
Referenced by ms_row_print().
MS_COL_INDEX_FORMAT
#define MS_COL_INDEX_FORMAT "%3d "
Definition at line 18 of file Board.c.
Referenced by ms_header_print().
MS_LINE_FORMAT
#define MS_LINE_FORMAT "----"
Definition at line 16 of file Board.c.
Referenced by ms_line_print().
MS_LINE_PREFIX
#define MS_LINE_PREFIX "\n "
Definition at line 15 of file Board.c.
Referenced by ms_header_print(), and ms_line_print().
MS_NUMBER_FORMAT
#define MS_NUMBER_FORMAT "%d"
Definition at line 9 of file Board.c.
Referenced by ms_cell_print().
MS_NUMBER_ZERO_FORMAT
#define MS_NUMBER_ZERO_FORMAT " "
Definition at line 10 of file Board.c.
Referenced by ms_cell_print().
MS_ROW_INDEX_FORMAT
#define MS_ROW_INDEX_FORMAT "\n%3d %s"
Definition at line 17 of file Board.c.
Referenced by ms_row_print().
NEW_LINE
#define NEW_LINE "\n"
Definition at line 8 of file Board.c.
Referenced by ms_board_print().
SPACE
#define SPACE " "
Definition at line 7 of file Board.c.
Function Documentation
ms_board_free()
void ms_board_free (ms_board * board)
Definition at line 208 of file Board.c.
References board::cells, ms_matrix_free(), and board::nb_rows.
Referenced by main().
ms_board_get()
ms_cell* ms_board_get (ms_board * board, int row, int col)
Definition at line 35 of file Board.c.
References board::cells, and ms_matrix_get().
Referenced by ms_board_open(), ms_board_open_cell(), ms_board_toggle_flag(), ms_board_update_nb_neighbours(), and ms_cell_update_nb_neighbours().
ms_board_make()
ms_board* ms_board_make (int nb_cols, int nb_rows, double bomb_ratio)
Definition at line 100 of file Board.c.
References board::cells, ms_board_update_nb_neighbours(), ms_matrix_make(), board::nb_bombs, board::nb_cols, board::nb_flags, board::nb_rows, and board::nb_shown.
Referenced by main().
ms_board_print()
void ms_board_print (ms_board * board)
Definition at line 178 of file Board.c.
References board::cells, MS_BOTTOM_FORMAT, ms_line_print(), ms_matrix_print(), board::nb_bombs, board::nb_cols, board::nb_flags, board::nb_rows, board::nb_shown, and NEW_LINE.
Referenced by ms_play(), and ms_play_once().
ms_board_update_nb_neighbours()
int ms_board_update_nb_neighbours (ms_board * board)
Definition at line 56 of file Board.c.
References ms_board_get(), ms_cell_update_nb_neighbours(), board::nb_cols, and board::nb_rows.
Referenced by ms_board_make().
ms_cell_make()
ms_cell ms_cell_make (double bomb_ratio)
Definition at line 72 of file Board.c.
References cell::is_bombed, cell::is_flagged, cell::is_shown, and cell::nb_neighbours.
Referenced by ms_row_make().
ms_cell_print()
void ms_cell_print (ms_cell cell)
Definition at line 117 of file Board.c.
References BOMB, FLAG, HIDDEN, cell::is_bombed, cell::is_flagged, cell::is_shown, MS_NUMBER_FORMAT, MS_NUMBER_ZERO_FORMAT, and cell::nb_neighbours.
Referenced by ms_row_print().
ms_cell_update_nb_neighbours()
void ms_cell_update_nb_neighbours (ms_board * board, int row, int col)
Definition at line 44 of file Board.c.
References cell::is_bombed, ms_board_get(), ms_max(), ms_min(), board::nb_cols, cell::nb_neighbours, and board::nb_rows.
Referenced by ms_board_update_nb_neighbours().
ms_header_print()
void ms_header_print (int nb_cols)
Definition at line 144 of file Board.c.
References MS_COL_INDEX_FORMAT, and MS_LINE_PREFIX.
Referenced by ms_matrix_print().
ms_line_print()
void ms_line_print (int nb_cols)
Definition at line 155 of file Board.c.
References MS_LINE_FORMAT, and MS_LINE_PREFIX.
Referenced by ms_board_print(), and ms_matrix_print().
ms_matrix_free()
void ms_matrix_free (ms_cell ** cells, int nb_rows)
Definition at line 200 of file Board.c.
References ms_row_free().
Referenced by ms_board_free().
ms_matrix_get()
ms_cell* ms_matrix_get (ms_cell ** cells, int row, int col)
Definition at line 30 of file Board.c.
References ms_row_get().
Referenced by ms_board_get().
ms_matrix_make()
ms_cell** ms_matrix_make (int nb_rows, int nb_cols, double bomb_ratio)
Definition at line 91 of file Board.c.
References ms_row_make().
Referenced by ms_board_make().
ms_matrix_print()
void ms_matrix_print (ms_cell ** cells, int nb_rows, int nb_cols)
Definition at line 166 of file Board.c.
References ms_header_print(), ms_line_print(), and ms_row_print().
Referenced by ms_board_print().
ms_row_free()
void ms_row_free (ms_cell * cells)
Definition at line 195 of file Board.c.
Referenced by ms_matrix_free().
ms_row_get()
ms_cell* ms_row_get (ms_cell * cells, int col)
Definition at line 25 of file Board.c.
Referenced by ms_matrix_get().
ms_row_make()
ms_cell* ms_row_make (int nb_cols, double bomb_ratio)
Definition at line 82 of file Board.c.
References ms_cell_make().
Referenced by ms_matrix_make().
ms_row_print()
void ms_row_print (ms_cell * cells, int row_index, int nb_cols)
Definition at line 131 of file Board.c.
References ms_cell_print(), MS_CELL_SEPARATOR, and MS_ROW_INDEX_FORMAT.
Referenced by ms_matrix_print().