Minesweeper: src/Minesweeper.c File Reference
Minesweeper.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "Actions.h"
#include "Util.h"
Macros
#define MS_OPEN_KEY 'O'
#define MS_FLAG_KEY 'F'
#define MS_ROW_PROMPT_FORMAT "Row (1, .., %d): "
#define MS_COL_PROMPT_FORMAT "Col (1, .., %d): "
#define MS_ACTION_PROMPT_FORMAT "Action (%c -> Open, %c -> Toggle flag) : "
#define MS_UNKNOWN_ACTION "Unknown action\n"
#define MS_WIN_MSG "You win !\n"
#define MS_LOSE_MSG "You lose !\n"
#define MS_CANNOT_FLAG_MSG "Cannot toggle flag of this cell !\n"
#define MS_CANNOT_OPEN_MSG "Cannot open this cell !\n"
#define MS_DEFAULT_NB_ROWS 10
#define MS_DEFAULT_NB_COLS 10
#define MS_DEFAULT_RATIO 0.2
Functions
int ms_play_once (ms_board *board)
int ms_play (ms_board *board)
int main (int argv, char **argc)
Macro Definition Documentation
MS_ACTION_PROMPT_FORMAT
#define MS_ACTION_PROMPT_FORMAT "Action (%c -> Open, %c -> Toggle flag) : "
Definition at line 12 of file Minesweeper.c.
Referenced by ms_play_once().
MS_CANNOT_FLAG_MSG
#define MS_CANNOT_FLAG_MSG "Cannot toggle flag of this cell !\n"
Definition at line 17 of file Minesweeper.c.
Referenced by ms_play().
MS_CANNOT_OPEN_MSG
#define MS_CANNOT_OPEN_MSG "Cannot open this cell !\n"
Definition at line 18 of file Minesweeper.c.
Referenced by ms_play().
MS_COL_PROMPT_FORMAT
#define MS_COL_PROMPT_FORMAT "Col (1, .., %d): "
Definition at line 11 of file Minesweeper.c.
Referenced by ms_play_once().
MS_DEFAULT_NB_COLS
#define MS_DEFAULT_NB_COLS 10
Definition at line 21 of file Minesweeper.c.
Referenced by main().
MS_DEFAULT_NB_ROWS
#define MS_DEFAULT_NB_ROWS 10
Definition at line 20 of file Minesweeper.c.
Referenced by main().
MS_DEFAULT_RATIO
#define MS_DEFAULT_RATIO 0.2
Definition at line 22 of file Minesweeper.c.
Referenced by main().
MS_FLAG_KEY
#define MS_FLAG_KEY 'F'
Definition at line 8 of file Minesweeper.c.
Referenced by ms_play_once().
MS_LOSE_MSG
#define MS_LOSE_MSG "You lose !\n"
Definition at line 16 of file Minesweeper.c.
Referenced by ms_play().
MS_OPEN_KEY
#define MS_OPEN_KEY 'O'
Definition at line 7 of file Minesweeper.c.
Referenced by ms_play_once().
MS_ROW_PROMPT_FORMAT
#define MS_ROW_PROMPT_FORMAT "Row (1, .., %d): "
Definition at line 10 of file Minesweeper.c.
Referenced by ms_play_once().
MS_UNKNOWN_ACTION
#define MS_UNKNOWN_ACTION "Unknown action\n"
Definition at line 13 of file Minesweeper.c.
Referenced by ms_play_once().
MS_WIN_MSG
#define MS_WIN_MSG "You win !\n"
Definition at line 15 of file Minesweeper.c.
Referenced by ms_play().
Function Documentation
main()
int main (int argv, char ** argc)
Definition at line 79 of file Minesweeper.c.
References ms_board_free(), ms_board_make(), MS_DEFAULT_NB_COLS, MS_DEFAULT_NB_ROWS, MS_DEFAULT_RATIO, and ms_play().
ms_play()
int ms_play (ms_board * board)
Definition at line 56 of file Minesweeper.c.
References ms_board_print(), MS_CANNOT_FLAG_CODE, MS_CANNOT_FLAG_MSG, MS_CANNOT_OPEN_CODE, MS_CANNOT_OPEN_MSG, MS_LOSE_CODE, MS_LOSE_MSG, ms_play_once(), MS_WIN_CODE, and MS_WIN_MSG.
Referenced by main().
ms_play_once()
int ms_play_once (ms_board * board)
Definition at line 26 of file Minesweeper.c.
References MS_ACTION_PROMPT_FORMAT, ms_board_open(), ms_board_print(), ms_board_toggle_flag(), MS_COL_PROMPT_FORMAT, MS_FLAG_KEY, ms_get_char(), ms_get_int(), MS_OPEN_KEY, MS_ROW_PROMPT_FORMAT, MS_UNKNOWN_ACTION, board::nb_cols, and board::nb_rows.
Referenced by ms_play().