Minesweeper: src/Util.c File Reference
Util.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int ms_min (int x, int y)
int ms_max (int x, int y)
int ms_get_char ()
int ms_get_int ()
Function Documentation
ms_get_char()
int ms_get_char ()
Definition at line 15 of file Util.c.
Referenced by ms_play_once().
ms_get_int()
int ms_get_int ()
Definition at line 24 of file Util.c.
Referenced by ms_play_once().
ms_max()
int ms_max (int x, int y)
Definition at line 10 of file Util.c.
References ms_min().
Referenced by ms_board_open_neighbours(), and ms_cell_update_nb_neighbours().
ms_min()
int ms_min (int x, int y)
Definition at line 5 of file Util.c.
Referenced by ms_board_open_neighbours(), ms_cell_update_nb_neighbours(), and ms_max().